function [rawCellColumns,rawNumericColumns] = importsumfile(filename,startRow,endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [COEF1,SDERR1,TSTAT1,PVAL1,COEF2,SDERR2,TSTAT2,PVAL2,COEF3,SDERR3,TSTAT3,PVAL3,COEF4,SDERR4,TSTAT4,PVAL4,VARNAME17]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [COEF1,SDERR1,TSTAT1,PVAL1,COEF2,SDERR2,TSTAT2,PVAL2,COEF3,SDERR3,TSTAT3,PVAL3,COEF4,SDERR4,TSTAT4,PVAL4,VARNAME17]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [COEF1,SDERR1,TSTAT1,PVAL1,COEF2,SDERR2,TSTAT2,PVAL2,COEF3,SDERR3,TSTAT3,PVAL3,COEF4,SDERR4,TSTAT4,PVAL4,VarName17]
%   = importfile('Summary_Post_Regression_Ratio_30sec_1.txt',2, 265);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/05/24 11:14:48

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]);
rawCellColumns = raw(:, 1);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
%COEF1 = rawCellColumns(:, 1);
%SDERR1 = cell2mat(rawNumericColumns(:, 1));
%TSTAT1 = cell2mat(rawNumericColumns(:, 2));
%PVAL1 = cell2mat(rawNumericColumns(:, 3));
%COEF2 = cell2mat(rawNumericColumns(:, 4));
%SDERR2 = cell2mat(rawNumericColumns(:, 5));
%TSTAT2 = cell2mat(rawNumericColumns(:, 6));
%PVAL2 = cell2mat(rawNumericColumns(:, 7));
%COEF3 = cell2mat(rawNumericColumns(:, 8));
%SDERR3 = cell2mat(rawNumericColumns(:, 9));
%TSTAT3 = cell2mat(rawNumericColumns(:, 10));
%PVAL3 = cell2mat(rawNumericColumns(:, 11));
%COEF4 = cell2mat(rawNumericColumns(:, 12));
%SDERR4 = cell2mat(rawNumericColumns(:, 13));
%TSTAT4 = cell2mat(rawNumericColumns(:, 14));
%PVAL4 = cell2mat(rawNumericColumns(:, 15));
%VarName17 = cell2mat(rawNumericColumns(:, 16));

