function [data] = importfile(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [COEF1,SDERR1,TSTAT1,PVAL1,COEF2,SDERR2,TSTAT2,PVAL2,COEF3,SDERR3,TSTAT3,PVAL3,COEF4,SDERR4,TSTAT4,PVAL4]
%   = IMPORTFILE(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   [COEF1,SDERR1,TSTAT1,PVAL1,COEF2,SDERR2,TSTAT2,PVAL2,COEF3,SDERR3,TSTAT3,PVAL3,COEF4,SDERR4,TSTAT4,PVAL4]
%   = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   [COEF1,SDERR1,TSTAT1,PVAL1,COEF2,SDERR2,TSTAT2,PVAL2,COEF3,SDERR3,TSTAT3,PVAL3,COEF4,SDERR4,TSTAT4,PVAL4]
%   = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   [COEF1,SDERR1,TSTAT1,PVAL1,COEF2,SDERR2,TSTAT2,PVAL2,COEF3,SDERR3,TSTAT3,PVAL3,COEF4,SDERR4,TSTAT4,PVAL4]
%   = importfile('Regression_Ratio_30sec_1.xlsx','Sheet1',2,257);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/05/24 14:14:32

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 249;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('B%d:Q%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('B%d:Q%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));


