rm(list=ls(all=TRUE))
library(car)
library(plm)
library(tseries)
library(openxlsx)
library(lmtest)
library(sandwich)
library(quantmod)
library(AER)

head<-"C:/DatiLocali/"
#head<-"C:/Users/Julia/"
windows<-c(120,60,30,10)
ticks<-c("AAPL","CSCO","EBAY","FB","GOOG","INTC","MSFT","YHOO")
folder<-"Individual_Post_Ratio"
mypath<-paste(head,"Dropbox/Projects/Trader Anonymity/Data/",sep="")

k<-3
w<-windows[k]

##SAVE FILE
filename<-paste(mypath,"DATA_INST_NOAAPL_",w,"sec.Rds",sep="")
load(file=filename)
ticks<-ticks[-1]

##RUN THROUGH DIFFERENT MODELS###################################

#  for (l in 1:20){

numregs<-31
numtest<-6
stationary<-matrix(NA,numregs,numtest*2*length(ticks))
##########
mpidlags<-1
depvarlags<-5
#lags<-l
##########
day.f<-factor(mydata$DAY)
DDUMMIES<-model.matrix(~day.f); DDUMMIES<-DDUMMIES[,2:ncol(DDUMMIES)]

for (jj in 8:numregs){

l.relspr1<-1
l.relspr2<-1
l.relspr3<-1
l.vol1<-1
l.vol2<-1
l.vol3<-1
l.sub<-1
l.sub.buy<-1
l.sub.sell<-1
l.exe<-1
l.exe.buy<-1
l.exe.sell<-1
l.d<-1
l.d.buy<-1
l.d.sell<-1
l.pr<-1

if(jj==1){
  l.relspr1<-depvarlags
  model<-RELSPR~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+
    LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+OPEN+abs(LAG.RELDPR.MID)+
    LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+SUB.ALL.NUM|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  model2<-RELSPR~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+
    LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+OPEN+abs(LAG.RELDPR.MID)+
    LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+SUB.ALL.NUM+DUMMIES|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
}
if(jj==2){
  l.relspr1<-depvarlags
  model<-RELSPR~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+OPEN+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+SUB.BUY.NUM|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
  model2<-RELSPR~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+OPEN+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+SUB.BUY.NUM+DUMMIES|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
}

if(jj==3){
  l.relspr1<-depvarlags
  model<-RELSPR~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+OPEN+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+SUB.SELL.NUM|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  model2<-RELSPR~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+OPEN+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+SUB.SELL.NUM+DUMMIES|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  
}
if(jj==4){
  l.relspr2<-depvarlags
  model<-RELEFFSPR.EXE.REP~LAG.MPID.SUB.RATIO+LAG.VOL.GRID.SHORT.PRE+LAG.RELEFFSPR.EXE.REP+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+OPEN+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+SUB.ALL.NUM|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  model2<-RELEFFSPR.EXE.REP~LAG.MPID.SUB.RATIO+LAG.VOL.GRID.SHORT.PRE+LAG.RELEFFSPR.EXE.REP+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+OPEN+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+SUB.ALL.NUM+DUMMIES|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  
}
if(jj==5){
  l.relspr3<-depvarlags
  model<-RELRLZSPR.EXE.REP.POST~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELRLZSPR.EXE.REP.PRE+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.ALL.NUM|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  model2<-RELRLZSPR.EXE.REP.POST~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELRLZSPR.EXE.REP.PRE+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.ALL.NUM+DUMMIES|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  
}
##VOLATILITY
if(jj==6){
  l.vol1<-depvarlags
  model<-VOL.GRID.SHORT.POST~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+OPEN+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+SUB.ALL.NUM|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  model2<-VOL.GRID.SHORT.POST~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+OPEN+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+SUB.ALL.NUM+DUMMIES|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  
}
if(jj==7){
  l.vol1<-depvarlags
  model<-VOL.GRID.SHORT.POST~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+OPEN+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+SUB.BUY.NUM|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
  model2<-VOL.GRID.SHORT.POST~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+OPEN+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+SUB.BUY.NUM+DUMMIES|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
  
}
if(jj==8){
  l.vol1<-depvarlags
  model<-VOL.GRID.SHORT.POST~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  model2<-VOL.GRID.SHORT.POST~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM+DUMMIES|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
}

if(jj==9){
  l.vol2<-depvarlags
  model<-VOL.SD~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.SD+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.ALL.NUM|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  model2<-VOL.SD~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.SD+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.ALL.NUM+DUMMIES|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
}

if(jj==10){
  l.vol3<-depvarlags
  model<-VOL.GRID.LONG.POST~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.LONG.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.ALL.NUM|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  model2<-VOL.GRID.LONG.POST~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.LONG.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.ALL.NUM+DUMMIES|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
}
##SUBMISSIONVOLUME
if(jj==11){
  l.sub<-depvarlags
  model<-SUB.ALL.DVOL~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.ALL.NUM|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  model2<-SUB.ALL.DVOL~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.ALL.NUM+DUMMIES|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  
}
if(jj==12){
  l.sub.buy<-depvarlags
  model<-SUB.BUY.DVOL~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.BUY.NUM|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
  model2<-SUB.BUY.DVOL~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.BUY.NUM+DUMMIES|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
  
}
if(jj==13){
  l.sub.sell<-depvarlags
  model<-SUB.SELL.DVOL~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  model2<-SUB.SELL.DVOL~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM+DUMMIES|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
}
if(jj==14){
  l.sub.buy<-depvarlags
  model<-SUB.BUY.DVOL~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  model2<-SUB.BUY.DVOL~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM+DUMMIES|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  
}
if(jj==15){
  l.sub.sell<-depvarlags
  model<-SUB.SELL.DVOL~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.BUY.NUM|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
  model2<-SUB.SELL.DVOL~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.BUY.NUM+DUMMIES|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
  
}
##EXECUTIONVOLUME
if(jj==16){
  l.exe<-depvarlags
  model<-EXE.ALL.DVOL~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.ALL.NUM|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  model2<-EXE.ALL.DVOL~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.ALL.NUM+DUMMIES|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  
}
if(jj==17){
  l.exe.buy<-depvarlags
  model<-EXE.BUY.DVOL~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.BUY.NUM|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
  model2<-EXE.BUY.DVOL~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.BUY.NUM+DUMMIES|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
  
}
if(jj==18){
  l.exe.sell<-depvarlags
  model<-EXE.SELL.DVOL~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  model2<-EXE.SELL.DVOL~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM+DUMMIES|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  
}
if(jj==19){
  l.exe.buy<-depvarlags
  model<-EXE.BUY.DVOL~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  model2<-EXE.BUY.DVOL~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM+DUMMIES|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  
}
if(jj==20){
  l.exe.sell<-depvarlags
  model<-EXE.SELL.DVOL~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.BUY.NUM|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
  model2<-EXE.SELL.DVOL~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.BUY.NUM+DUMMIES|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
} 
##DEPTH
if(jj==21){
  l.d<-depvarlags
  model<-DEPTH.TOTAL.DVOL~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.ALL.NUM|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  model2<-DEPTH.TOTAL.DVOL~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.ALL.NUM+DUMMIES|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  
}
if(jj==22){
  l.d.buy<-depvarlags
  model<-DEPTH.BUY.DVOL~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.BUY.NUM|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
  model2<-DEPTH.BUY.DVOL~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.BUY.NUM+DUMMIES|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
  
}
if(jj==23){
  l.d.sell<-depvarlags
  model<-DEPTH.SELL.DVOL~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  model2<-DEPTH.SELL.DVOL~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM+DUMMIES|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  
}
if(jj==24){
  l.d.buy<-depvarlags
  model<-DEPTH.BUY.DVOL~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  model2<-DEPTH.BUY.DVOL~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM+DUMMIES|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  
}
if(jj==25){
  l.d.sell<-depvarlags
  model<-DEPTH.SELL.DVOL~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.BUY.NUM|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
  model2<-DEPTH.SELL.DVOL~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.BUY.NUM+DUMMIES|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
} 
##HASBROUCK
if(jj==26){
  l.h<-depvarlags
  model<-HASBROUCK.MAX~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.ALL.NUM|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  model2<-HASBROUCK.MAX~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.ALL.NUM+DUMMIES|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
}
if(jj==27){
  l.h<-depvarlags
  model<-HASBROUCK.MAX~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.BUY.NUM|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
  model2<-HASBROUCK.MAX~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.BUY.NUM+DUMMIES|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
}
if(jj==28){
  l.h<-depvarlags
  model<-HASBROUCK.MAX~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  model2<-HASBROUCK.MAX~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+abs(LAG.RELDPR.MID)+LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+OPEN+SUB.SELL.NUM+DUMMIES|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
}
##RELATIVE PRICE CHANGES
if(jj==29){
  l.pr<-depvarlags
  model<-RELDPR.MID~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+LAG.RELDPR.MID+OPEN+SUB.ALL.NUM|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
  model2<-RELDPR.MID~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+LAG.RELDPR.MID+OPEN+SUB.ALL.NUM+DUMMIES|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST
}
if(jj==30){
  l.pr<-depvarlags
  model<-RELDPR.MID~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+LAG.RELDPR.MID+OPEN+SUB.BUY.NUM|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
  model2<-RELDPR.MID~LAG.MPID.SUB.BUY.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.BUY.DVOL+LAG.EXE.BUY.DVOL+LAG.DEPTH.BUY.DVOL+LAG.RELDPR.MID+OPEN+SUB.BUY.NUM+DUMMIES|.-LAG.MPID.SUB.BUY.RATIO+LAG.MPID.SUB.BUY.INST-SUB.BUY.NUM+SUB.BUY.NUM.INST
}
if(jj==31){
  l.pr<-depvarlags
  model<-RELDPR.MID~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+LAG.RELDPR.MID+OPEN+SUB.SELL.NUM|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
  model2<-RELDPR.MID~LAG.MPID.SUB.SELL.RATIO+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+LAG.HASBROUCK.MAX+LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.SELL.DVOL+LAG.EXE.SELL.DVOL+LAG.DEPTH.SELL.DVOL+LAG.RELDPR.MID+OPEN+SUB.SELL.NUM+DUMMIES|.-LAG.MPID.SUB.SELL.RATIO+LAG.MPID.SUB.SELL.INST-SUB.SELL.NUM+SUB.SELL.NUM.INST
}


#model<-RELSPR~LAG.MPID.SUB.RATIO+LAG.AGGR.REL.TOTAL+LAG.ORSZ.DVOL.TOTAL+LAG.AGGR.REL.MPID+LAG.ORSZ.DVOL.MPID+
#  LAG.VOL.GRID.SHORT.PRE+LAG.RELSPR+LAG.SUB.ALL.DVOL+LAG.EXE.ALL.DVOL+LAG.DEPTH.TOTAL.DVOL+OPEN+abs(LAG.RELDPR.MID)+
#  LAG.NEG.DUMMY+(abs(LAG.RELDPR.MID)*LAG.NEG.DUMMY)+SUB.ALL.NUM|.-LAG.MPID.SUB.RATIO+LAG.MPID.SUB.INST-SUB.ALL.NUM+SUB.ALL.NUM.INST

filename<-paste(mypath,"Results/", folder, "/Post_Regression_Ratio_",w,"sec_",jj,".txt",sep="")
cat(paste("\n \n","Firm-Level Regression #", jj, ", Dep Var: ",all.vars(model)[2],"\n \n",sep=""),file=filename,append=FALSE)

ii<-1

mydata_temp<-mydata[mydata$TICK==ii,]

SUB.ALL.NUM<-Lag(mydata_temp$SUB.ALL.NUM,k=1:mpidlags)
SUB.BUY.NUM<-Lag(mydata_temp$SUB.BUY.NUM,k=1:mpidlags)
SUB.SELL.NUM<-Lag(mydata_temp$SUB.SELL.NUM,k=1:mpidlags)
SUB.ALL.NUM.INST<-Lag(mydata_temp$SUB.ALL.NUM.INST,k=1:mpidlags)
SUB.BUY.NUM.INST<-Lag(mydata_temp$SUB.BUY.NUM.INST,k=1:mpidlags)
SUB.SELL.NUM.INST<-Lag(mydata_temp$SUB.SELL.NUM.INST,k=1:mpidlags)

MPID.SUB.RATIO<-mydata_temp$MPID.SUB.RATIO
MPID.SUB.BUY.RATIO<-mydata_temp$MPID.SUB.BUY.RATIO
MPID.SUB.SELL.RATIO<-mydata_temp$MPID.SUB.BUY.RATIO

LAG.MPID.SUB.RATIO<-Lag(mydata_temp$MPID.SUB.RATIO,k=1:mpidlags)
LAG.MPID.SUB.BUY.RATIO<-Lag(mydata_temp$MPID.SUB.BUY.RATIO,k=1:mpidlags)
LAG.MPID.SUB.SELL.RATIO<-Lag(mydata_temp$MPID.SUB.BUY.RATIO,k=1:mpidlags)
LAG.MPID.SUB.INST<-Lag(mydata_temp$MPID.SUB.INST,k=1:mpidlags)
LAG.MPID.SUB.BUY.INST<-Lag(mydata_temp$MPID.SUB.BUY.INST,k=1:mpidlags)
LAG.MPID.SUB.SELL.INST<-Lag(mydata_temp$MPID.SUB.BUY.INST,k=1:mpidlags)

AGGR.REL.MPID<-mydata_temp$AGGR.REL.MPID
ORSZ.DVOL.MPID<-mydata_temp$ORSZ.DVOL.MPID
AGGR.REL.TOTAL<-mydata_temp$AGGR.REL.TOTAL
ORSZ.DVOL.TOTAL<-mydata_temp$ORSZ.DVOL.TOTAL
VOL.GRID.SHORT.PRE<-mydata_temp$VOL.GRID.SHORT.PRE
VOL.GRID.LONG.PRE<-mydata_temp$VOL.GRID.LONG.PRE
VOL.GRID.SHORT.POST<-mydata_temp$VOL.GRID.SHORT.POST
VOL.GRID.LONG.POST<-mydata_temp$VOL.GRID.LONG.POST
VOL.SD<-mydata_temp$VOL.SD 
RELSPR<-mydata_temp$RELSPR
RELEFFSPR.EXE.REP<-mydata_temp$RELEFFSPR.EXE.REP
RELRLZSPR.EXE.REP.PRE<-mydata_temp$RELRLZSPR.EXE.REP.PRE
RELRLZSPR.EXE.REP.POST<-mydata_temp$RELRLZSPR.EXE.REP.POST
SUB.ALL.DVOL<-mydata_temp$SUB.ALL.DVOL
EXE.ALL.DVOL<-mydata_temp$EXE.ALL.DVOL
SUB.BUY.DVOL<-mydata_temp$SUB.BUY.DVOL
EXE.BUY.DVOL<-mydata_temp$EXE.BUY.DVOL
SUB.SELL.DVOL<-mydata_temp$SUB.SELL.DVOL
EXE.SELL.DVOL<-mydata_temp$EXE.SELL.DVOL
DEPTH.TOTAL.DVOL<-mydata_temp$DEPTH.TOTAL.DVOL
DEPTH.BUY.DVOL<-mydata_temp$DEPTH.TOTAL.DVOL
DEPTH.SELL.DVOL<-mydata_temp$DEPTH.TOTAL.DVOL
RELDPR.MID<-mydata_temp$RELDPR.MID
NEG.DUMMY<-mydata_temp$NEG.DUMMY
HASBROUCK.MAX<-mydata_temp$HASBROUCK.MAX

LAG.AGGR.REL.MPID<-Lag(mydata_temp$AGGR.REL.MPID,k=1)
LAG.ORSZ.DVOL.MPID<-Lag(mydata_temp$ORSZ.DVOL.MPID,k=1)
LAG.AGGR.REL.TOTAL<-Lag(mydata_temp$AGGR.REL.TOTAL,k=1)
LAG.ORSZ.DVOL.TOTAL<-Lag(mydata_temp$ORSZ.DVOL.TOTAL,k=1)
LAG.VOL.GRID.SHORT.PRE<-Lag(mydata_temp$VOL.GRID.SHORT.PRE,k=1:l.vol1)
LAG.VOL.GRID.LONG.PRE<-Lag(mydata_temp$VOL.GRID.LONG.PRE,k=1:l.vol3)
LAG.VOL.GRID.SHORT.POST<-Lag(mydata_temp$VOL.GRID.SHORT.POST,k=1:l.vol1)
LAG.VOL.GRID.LONG.POST<-Lag(mydata_temp$VOL.GRID.LONG.POST,k=1:l.vol3)
LAG.VOL.SD<-Lag(mydata_temp$VOL.SD,k=1:l.vol2)
LAG.RELSPR<-Lag(mydata_temp$RELSPR,k=1:l.relspr1)
LAG.RELEFFSPR.EXE.REP<-Lag(mydata_temp$RELEFFSPR.EXE.REP,k=1:l.relspr2)
LAG.RELRLZSPR.EXE.REP.PRE<-Lag(mydata_temp$RELRLZSPR.EXE.REP.PRE,k=1:l.relspr3)
LAG.RELRLZSPR.EXE.REP.POST<-Lag(mydata_temp$RELRLZSPR.EXE.REP.POST,k=1:l.relspr3)
LAG.SUB.ALL.DVOL<-Lag(mydata_temp$SUB.ALL.DVOL,k=1:l.sub)
LAG.EXE.ALL.DVOL<-Lag(mydata_temp$EXE.ALL.DVOL,k=1:l.exe)
LAG.SUB.BUY.DVOL<-Lag(mydata_temp$SUB.BUY.DVOL,k=1:l.sub.buy)
LAG.EXE.BUY.DVOL<-Lag(mydata_temp$EXE.BUY.DVOL,k=1:l.exe.buy)
LAG.SUB.SELL.DVOL<-Lag(mydata_temp$SUB.SELL.DVOL,k=1:l.sub.sell)
LAG.EXE.SELL.DVOL<-Lag(mydata_temp$EXE.SELL.DVOL,k=1:l.exe.sell)
LAG.DEPTH.TOTAL.DVOL<-Lag(mydata_temp$DEPTH.TOTAL.DVOL,k=1:l.d)
LAG.DEPTH.BUY.DVOL<-Lag(mydata_temp$DEPTH.TOTAL.DVOL,k=1:l.d.buy)
LAG.DEPTH.SELL.DVOL<-Lag(mydata_temp$DEPTH.TOTAL.DVOL,k=1:l.d.sell)
LAG.RELDPR.MID<-Lag(mydata_temp$RELDPR.MID,k=1:l.pr)
LAG.NEG.DUMMY<-Lag(mydata_temp$NEG.DUMMY,k=1)
LAG.HASBROUCK.MAX<-Lag(mydata_temp$HASBROUCK.MAX,k=1)

OPEN<-mydata_temp$OPEN
CLOSE<-mydata_temp$CLOSE

DUMMIES<-DDUMMIES[mydata$TICK==ii,]
fit<-ivreg(model2)
s<-summary(fit)

rr<-nrow(s$coefficients)
t<-length(ticks)

formatlab<-matrix(NA,t*rr,4*4)
colnames(formatlab)<-c("COEF1","SD.ERR1","T.STAT1","P.VAL1","COEF2","SD.ERR2","T.STAT2","P.VAL2","COEF3","SD.ERR3","T.STAT3","P.VAL3","COEF4","SD.ERR4","T.STAT4","P.VAL4")
rowns<-matrix(NA,t*rr)

for (ii in 1:length(ticks)){   
  
  mydata_temp<-mydata[mydata$TICK==ii,]
  
  SUB.ALL.NUM<-Lag(mydata_temp$SUB.ALL.NUM,k=1:mpidlags)
  SUB.BUY.NUM<-Lag(mydata_temp$SUB.BUY.NUM,k=1:mpidlags)
  SUB.SELL.NUM<-Lag(mydata_temp$SUB.SELL.NUM,k=1:mpidlags)
  SUB.ALL.NUM.INST<-Lag(mydata_temp$SUB.ALL.NUM.INST,k=1:mpidlags)
  SUB.BUY.NUM.INST<-Lag(mydata_temp$SUB.BUY.NUM.INST,k=1:mpidlags)
  SUB.SELL.NUM.INST<-Lag(mydata_temp$SUB.SELL.NUM.INST,k=1:mpidlags)
  
  MPID.SUB.RATIO<-mydata_temp$MPID.SUB.RATIO
  MPID.SUB.BUY.RATIO<-mydata_temp$MPID.SUB.BUY.RATIO
  MPID.SUB.SELL.RATIO<-mydata_temp$MPID.SUB.BUY.RATIO
  
  LAG.MPID.SUB.RATIO<-Lag(mydata_temp$MPID.SUB.RATIO,k=1:mpidlags)
  LAG.MPID.SUB.BUY.RATIO<-Lag(mydata_temp$MPID.SUB.BUY.RATIO,k=1:mpidlags)
  LAG.MPID.SUB.SELL.RATIO<-Lag(mydata_temp$MPID.SUB.BUY.RATIO,k=1:mpidlags)
  LAG.MPID.SUB.INST<-Lag(mydata_temp$MPID.SUB.INST,k=1:mpidlags)
  LAG.MPID.SUB.BUY.INST<-Lag(mydata_temp$MPID.SUB.BUY.INST,k=1:mpidlags)
  LAG.MPID.SUB.SELL.INST<-Lag(mydata_temp$MPID.SUB.BUY.INST,k=1:mpidlags)
  
  AGGR.REL.MPID<-mydata_temp$AGGR.REL.MPID
  ORSZ.DVOL.MPID<-mydata_temp$ORSZ.DVOL.MPID
  AGGR.REL.TOTAL<-mydata_temp$AGGR.REL.TOTAL
  ORSZ.DVOL.TOTAL<-mydata_temp$ORSZ.DVOL.TOTAL
  VOL.GRID.SHORT.PRE<-mydata_temp$VOL.GRID.SHORT.PRE
  VOL.GRID.LONG.PRE<-mydata_temp$VOL.GRID.LONG.PRE
  VOL.GRID.SHORT.POST<-mydata_temp$VOL.GRID.SHORT.POST
  VOL.GRID.LONG.POST<-mydata_temp$VOL.GRID.LONG.POST
  VOL.SD<-mydata_temp$VOL.SD 
  RELSPR<-mydata_temp$RELSPR
  RELEFFSPR.EXE.REP<-mydata_temp$RELEFFSPR.EXE.REP
  RELRLZSPR.EXE.REP.PRE<-mydata_temp$RELRLZSPR.EXE.REP.PRE
  RELRLZSPR.EXE.REP.POST<-mydata_temp$RELRLZSPR.EXE.REP.POST
  SUB.ALL.DVOL<-mydata_temp$SUB.ALL.DVOL
  EXE.ALL.DVOL<-mydata_temp$EXE.ALL.DVOL
  SUB.BUY.DVOL<-mydata_temp$SUB.BUY.DVOL
  EXE.BUY.DVOL<-mydata_temp$EXE.BUY.DVOL
  SUB.SELL.DVOL<-mydata_temp$SUB.SELL.DVOL
  EXE.SELL.DVOL<-mydata_temp$EXE.SELL.DVOL
  DEPTH.TOTAL.DVOL<-mydata_temp$DEPTH.TOTAL.DVOL
  DEPTH.BUY.DVOL<-mydata_temp$DEPTH.TOTAL.DVOL
  DEPTH.SELL.DVOL<-mydata_temp$DEPTH.TOTAL.DVOL
  RELDPR.MID<-mydata_temp$RELDPR.MID
  NEG.DUMMY<-mydata_temp$NEG.DUMMY
  HASBROUCK.MAX<-mydata_temp$HASBROUCK.MAX
  
  LAG.AGGR.REL.MPID<-Lag(mydata_temp$AGGR.REL.MPID,k=1)
  LAG.ORSZ.DVOL.MPID<-Lag(mydata_temp$ORSZ.DVOL.MPID,k=1)
  LAG.AGGR.REL.TOTAL<-Lag(mydata_temp$AGGR.REL.TOTAL,k=1)
  LAG.ORSZ.DVOL.TOTAL<-Lag(mydata_temp$ORSZ.DVOL.TOTAL,k=1)
  LAG.VOL.GRID.SHORT.PRE<-Lag(mydata_temp$VOL.GRID.SHORT.PRE,k=1:l.vol1)
  LAG.VOL.GRID.LONG.PRE<-Lag(mydata_temp$VOL.GRID.LONG.PRE,k=1:l.vol3)
  LAG.VOL.GRID.SHORT.POST<-Lag(mydata_temp$VOL.GRID.SHORT.POST,k=1:l.vol1)
  LAG.VOL.GRID.LONG.POST<-Lag(mydata_temp$VOL.GRID.LONG.POST,k=1:l.vol3)
  LAG.VOL.SD<-Lag(mydata_temp$VOL.SD,k=1:l.vol2)
  LAG.RELSPR<-Lag(mydata_temp$RELSPR,k=1:l.relspr1)
  LAG.RELEFFSPR.EXE.REP<-Lag(mydata_temp$RELEFFSPR.EXE.REP,k=1:l.relspr2)
  LAG.RELRLZSPR.EXE.REP.PRE<-Lag(mydata_temp$RELRLZSPR.EXE.REP.PRE,k=1:l.relspr3)
  LAG.RELRLZSPR.EXE.REP.POST<-Lag(mydata_temp$RELRLZSPR.EXE.REP.POST,k=1:l.relspr3)
  LAG.SUB.ALL.DVOL<-Lag(mydata_temp$SUB.ALL.DVOL,k=1:l.sub)
  LAG.EXE.ALL.DVOL<-Lag(mydata_temp$EXE.ALL.DVOL,k=1:l.exe)
  LAG.SUB.BUY.DVOL<-Lag(mydata_temp$SUB.BUY.DVOL,k=1:l.sub.buy)
  LAG.EXE.BUY.DVOL<-Lag(mydata_temp$EXE.BUY.DVOL,k=1:l.exe.buy)
  LAG.SUB.SELL.DVOL<-Lag(mydata_temp$SUB.SELL.DVOL,k=1:l.sub.sell)
  LAG.EXE.SELL.DVOL<-Lag(mydata_temp$EXE.SELL.DVOL,k=1:l.exe.sell)
  LAG.DEPTH.TOTAL.DVOL<-Lag(mydata_temp$DEPTH.TOTAL.DVOL,k=1:l.d)
  LAG.DEPTH.BUY.DVOL<-Lag(mydata_temp$DEPTH.TOTAL.DVOL,k=1:l.d.buy)
  LAG.DEPTH.SELL.DVOL<-Lag(mydata_temp$DEPTH.TOTAL.DVOL,k=1:l.d.sell)
  LAG.RELDPR.MID<-Lag(mydata_temp$RELDPR.MID,k=1)
  LAG.NEG.DUMMY<-Lag(mydata_temp$NEG.DUMMY,k=1)
  LAG.HASBROUCK.MAX<-Lag(mydata_temp$HASBROUCK.MAX,k=1)
  
  OPEN<-mydata_temp$OPEN
  CLOSE<-mydata_temp$CLOSE  
  DUMMIES<-DDUMMIES[mydata$TICK==ii,]

  fit<-ivreg(model)
  s<-summary(fit)
  ss<-coeftest(fit, vcov=vcovHAC(fit))
  
  r<-length(names(fit$coefficients))
  formatlab[(rr*(ii-1)+1):(rr*(ii-1)+r),1:4]<-unname(s$coefficients)
  formatlab[(rr*(ii-1)+1):(rr*(ii-1)+r),5:8]<-unname(ss)
  
  cat(paste("\n \n",ticks[ii], " Regression #", jj, ", Dep Var: ",all.vars(model)[2],"\n \n",sep=""),file=filename,append=TRUE)
  capture.output(s, file=filename,append=TRUE)
  capture.output(ss, file=filename,append=T)
  
  fit<-ivreg(model2)
  s<-summary(fit)
  ss<-coeftest(fit, vcov=vcovHAC(fit))
  
  cat(paste("\n \n",ticks[ii], " Regression + Day Dummies #", jj, ", Dep Var: ",all.vars(model)[2],"\n \n",sep=""),file=filename,append=TRUE)
  capture.output(s, file=filename,append=TRUE)
  capture.output(ss, file=filename,append=T)
  
  formatlab[(rr*(ii-1)+1):(rr*(ii-1)+rr),9:12]<-unname(s$coefficients)
  formatlab[(rr*(ii-1)+1):(rr*(ii-1)+rr),13:16]<-unname(ss)
  row<-paste(ticks[ii],".",names(fit$coefficients),sep="")
  rowns[(rr*(ii-1)+1):(rr*(ii-1)+rr)]<-row  
  
  v<-unname(residuals(fit))
  
 # pdf(paste(mypath,"/Graphs/", folder, "_Errors/",ticks[ii],"_IndividualErrors_Ratio_",jj,"_",w,"sec.pdf",sep=""))
#  plot(v,type = "l",ylab="Panel Errors",main=ticks[ii],xlab="Date")
#  dev.off()
  
  test1<-adf.test(v)
  test2<-PP.test(v,lshort=FALSE)
  test3<-kpss.test(v,null=c("Level"))
  test4<-kpss.test(v,null=c("Trend"))
  #test5<-dwtest(model,alternative="two.sided")
  test5<-Box.test(v, lag=(2*mpidlags), type = c("Ljung-Box"),fitdf=(mpidlags))
  test6<-summary(lm(v[-1]~v[-length(v)]))
  #test7<-Box.test(v, lag=(2*lags), type = c("Ljung-Box"),fitdf=(lags))
  
  stationary[jj,(1+(numtest*2)*(ii-1)):((numtest*2)+(numtest*2)*(ii-1))]<-c(test1$statistic,test1$p.value,test2$statistic,test2$p.value,
                                                                            test3$statistic,test3$p.value,test4$statistic,test4$p.value,
                                                                            test5$statistic,test5$p.value,
                                                                            test6$coefficients[2,3],test6$coefficients[2,4])
  #filename2<-paste(mypath,"Results/", folder, "/Regression_Ratio_",ticks[ii],"_",w,"sec_",jj,".rda",sep="")
  #save(fit,file=filename2)
  
}


rownames(formatlab)<-rowns
write.xlsx(formatlab, paste(mypath,"Results/", folder, "/Post_Regression_Ratio_",w,"sec_",jj,".xlsx",sep=""))

}


#colnames(stationary)<-c('AAPL',vector(mode="numeric",length=(2*numtest-1)),'CSCO',vector(mode="numeric",length=(2*numtest-1)),
#                        'EBAY',vector(mode="numeric",length=(2*numtest-1)),'FB',vector(mode="numeric",length=(2*numtest-1)),
#                        'GOOG',vector(mode="numeric",length=(2*numtest-1)),
#                        'INTC',vector(mode="numeric",length=(2*numtest-1)),'MSFT',vector(mode="numeric",length=(2*numtest-1)),
#                        'YHOO',vector(mode="numeric",length=(2*numtest-1)))

colnames(stationary)<-c('CSCO',vector(mode="numeric",length=(2*numtest-1)),
                        'EBAY',vector(mode="numeric",length=(2*numtest-1)),'FB',vector(mode="numeric",length=(2*numtest-1)),
                        'GOOG',vector(mode="numeric",length=(2*numtest-1)),
                        'INTC',vector(mode="numeric",length=(2*numtest-1)),'MSFT',vector(mode="numeric",length=(2*numtest-1)),
                        'YHOO',vector(mode="numeric",length=(2*numtest-1)))



filename<-paste(mypath,"Results/",folder,"/INDIVIDUALERRORS_STATIONARITY_BYFIRM_",mpidlags,"MPIDLags_",depvarlags,"DepVarLags_",w,"sec.xlsx",sep="")
write.xlsx(stationary,file=filename,append=FALSE) 


#}




